HurtowniaLekow/config/routes.rb
HurtowniaLekow::Application.routes.draw do

  resources :zamowienies

  
  resources :pracowniks, :path => "/editpracowniks"

  resources :admins, :controller => :pracowniks, :path => "/editpracowniks"

  resources :producents

  resources :leks

  devise_for :klients

  devise_for :pracowniks, :controllers => { :registrations => "pracowniks/registrations" }

  devise_for :admins, :controllers => { :registrations => "admins/registrations" }
  
  get "stronaglowna/index"
  

  match '/zamowienies/new' => 'zamowienies#new'
  match '/' => 'stronaglowna#index', :as => :index
  match '/leks' => 'leks#index', :as => :leksindex
  match '/zamowienies' => 'zamowienies#index', :as => :zamowieniesindex
  match '/producents' => 'producents#index', :as => :producentsindex
  match '/editpracowniks' => 'pracowniks#index', :as => :pracowniksindex
  
  
  

  root :to => "stronaglowna#index"

end

HurtowniaLekow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HurtowniaLekow</title>
<link rel="stylesheet" href="/stylesheets/blueprint/screen.css" type="text/css" media="screen, projection" />
<link rel="stylesheet" href="/stylesheets/blueprint/print.css" type="text/css" media="print" />
<!--[if lt IE 8]>
  <link rel="stylesheet" href="/stylesheets/blueprint/ie.css" type="text/css" media="screen, projection" />
<![endif]-->
<!-- nie chcemy chyba tych archaicznych buttonow
<link rel="stylesheet" href="/stylesheets/blueprint/plugins/buttons/screen.css" type="text/css" media="screen, projection" />
-->
<link rel="stylesheet" href="/stylesheets/style.css" type="text/css" media="screen, projection" />



<%= javascript_include_tag 'jquery-1.6', 'rails.validations', :defaults -%>
<%= csrf_meta_tag %>

</head>
<body>
<div class="container">
	<div class="top"></div>
	<br />
        <% if !alert.nil? %>
          <p class="alert"><%= alert %></p>
        <% end %>
        <% if !notice.nil? %>
          <p class="notice"><%= notice %></p>
        <% end %>
        
          <%- if pracownik_signed_in? %>
            <div id="userpanel" class="tablebg">
              <p>
            <%= "Zalogowany jako #{current_pracownik.email}." %>
            <%= link_to 'Wyloguj się', destroy_pracownik_session_path %>
              </p>
            </div>
          <%- elsif klient_signed_in? %>
            <div id="userpanel" class="tablebg">
              <p>
            <%= "Zalogowany jako #{current_klient.email}." %>
            <%= link_to 'Wyloguj się', destroy_klient_session_path %>
              </p>
            </div>
          <%- else %>
          <p>Witaj, zaloguj się jako <%= link_to 'klient', new_klient_session_path %>
            bądź <%= link_to 'pracownik', new_pracownik_session_path %>, by móc zacząć korzystać z funkcjonalności systemu.</p>
          <%- end %>
        <p></p>
	<div id="sidebar">
		<ul>			
                        <li><%= link_to "Strona główna", :index, :title => "Przejście do strony głównej systemu" %> </li>
                        <li><%= link_to "O nas", :index, :title => "Informacje o hurtowni" %> </li>

                        <%- if klient_signed_in? %>
                          <li><%= link_to "Leki", :leksindex, :title => "Oferta leków naszej hurtowni" %> </li>
                          <li><%= link_to "Zamówienia", :zamowieniesindex, :title => "Bieżące zamówienia" %> </li>
                          <li><%= link_to "Historia", :index, :title => "Historia zamówień" %> </li>
                        <%- elsif pracownik_signed_in? and current_pracownik.type == "Admin" %>
                          <li><%= link_to "Producenci", :producentsindex, :title => "Zarządzaj producentami" %> </li>
                          <li><%= link_to "Pracownicy", :pracowniksindex, :title => "Zarządzaj pracownikami" %> </li>
                          <li><%= link_to "Leki", :leksindex, :title => "Zarządzaj lekami" %> </li>
                        <%- elsif pracownik_signed_in? %>
                          <li><%= link_to "Zamówienia", :index, :title => "Zamówienia oczekujące na realizację" %> </li>
                        <%- end %>
                        <% if can? :manage, @pracownik %>
                          <li><%= link_to "Zarejestruj pracownika", '/pracowniks/sign_up', :title => "Zarejestruj nowego pracownika" %> </li>
                        <%- end %>
                        <% if can? :manage, @admin %>
                          <li><%= link_to "Zarejestruj administratora", '/admins/sign_up', :title => "Zarejestruj nowego administratora" %> </li>
                        <%- end %>
                </ul>
	</div>
        <div class="content">
                <%= yield %>
               
 <!-- przyklady przyciskow - mozesz odkomentowac razem z linkiem do css w headzie
                <button type="submit" class="button positive">
    <img src="stylesheets/blueprint/plugins/buttons/icons/tick.png" alt=""/> Save
  </button>

  <a class="button" href="/password/reset/">
    <img src="stylesheets/blueprint/plugins/buttons/icons/key.png" alt=""/> Change Password
  </a>

  <a href="#" class="button negative">
    <img src="stylesheets/blueprint/plugins/buttons/icons/cross.png" alt=""/> Cancel
  </a>
 -->
        </div>
        <div class="footer">Copyright Jakub Bomba, Jacek Cisło</div>
</div>
</body>
</html>