HurtowniaLekow/config/routes.rb
HurtowniaLekow::Application.routes.draw do

  resources :zamowienies

  
  resources :pracowniks, :path => "/editpracowniks"

  resources :admins, :controller => :pracowniks, :path => "/editpracowniks"

  resources :producents

  resources :leks

  devise_for :klients

  devise_for :pracowniks, :controllers => { :registrations => "pracowniks/registrations" }

  devise_for :admins, :controllers => { :registrations => "admins/registrations" }
  
  get "stronaglowna/index"
  

  match '/zamowienies/new' => 'zamowienies#new'
  match '/' => 'stronaglowna#index', :as => :index
  match '/leks' => 'leks#index', :as => :leksindex
  match '/zamowienies' => 'zamowienies#index', :as => :zamowieniesindex
  match '/producents' => 'producents#index', :as => :producentsindex
  match '/editpracowniks' => 'pracowniks#index', :as => :pracowniksindex
  
  
  

  root :to => "stronaglowna#index"

end

HurtowniaLekow/app/models/lek.rb
class Lek < ActiveRecord::Base
  validates :producent_id, :presence => true
  validates :NazwaLeku, :presence => true  
  validates :Cena, :presence => true
  validates :Ilosc, :presence => true

  belongs_to :producent
  has_many :zamowienies
  has_many :dostawas
end

HurtowniaLekow/app/controllers/leks_controller.rb
class LeksController < ApplicationController
load_and_authorize_resource

   
  # GET /leks
  # GET /leks.xml
  def index
    @leks = Lek.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @leks }
    end
  end

  # GET /leks/1
  # GET /leks/1.xml
  def show
    @lek = Lek.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lek }
    end
  end

  # GET /leks/new
  # GET /leks/new.xml
  def new
    @lek = Lek.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lek }
    end
  end

  # GET /leks/1/edit
  def edit
    @lek = Lek.find(params[:id])
  end

  # POST /leks
  # POST /leks.xml
  def create
    @lek = Lek.new(params[:lek])

    respond_to do |format|
      if @lek.save
        format.html { redirect_to(@lek, :notice => 'Lek was successfully created.') }
        format.xml  { render :xml => @lek, :status => :created, :location => @lek }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lek.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /leks/1
  # PUT /leks/1.xml
  def update
    @lek = Lek.find(params[:id])

    respond_to do |format|
      if @lek.update_attributes(params[:lek])
        format.html { redirect_to(@lek, :notice => 'Lek was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lek.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /leks/1
  # DELETE /leks/1.xml
  def destroy
    @lek = Lek.find(params[:id])
    @lek.destroy
    

    respond_to do |format|
      format.html { redirect_to(leks_url) }
      format.xml  { head :ok }
    end
  end
end

HurtowniaLekow/app/helpers/leks_helper.rb
module LeksHelper
end

HurtowniaLekow/app/views/leks/_form.html.erb
<%= form_for(@lek, :validate => true) do |f| %>
  <% if @lek.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lek.errors.count, "error") %> prohibited this lek from being saved:</h2>

      <ul>
      <% @lek.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Nazwa %><br />
    <%= f.text_field :NazwaLeku %>
  </div>
  <div class="field">
    <%= f.label :Producent %><br />
    <%= collection_select(:lek, :producent_id, Producent.all, :id, :NazwaProducenta) %><br />    
  </div>
  <div class="field">
    <%= f.label :Cena %><br />
    <%= f.text_field :Cena %>
  </div>
  <div class="field">
    <%= f.label :Ilość %><br />
    <%= f.text_field :Ilosc %>
  </div>

  <div class="actions">
    <%= f.submit :Wyślij %>
  </div>
<% end %>

HurtowniaLekow/app/views/leks/edit.html.erb
<h1>Edycja leku</h1>

<%= render 'form' %>

<%= link_to 'Pokaż', @lek %> |
<%= link_to 'Powrót', leks_path %>

HurtowniaLekow/app/views/leks/index.html.erb
<h1>Lista leków</h1>

<table>
  <tr>
    <th>Nazwa</th>
    <th>Producent</th>
    <th>Cena</th>
    <th>Ilość</th>    
    
    <% if can? :read, @lek %><th></th><%- end %>
    <% if can? :update, @lek %><th></th><%- end %>
    <% if can? :cancel, @lek %><th></th><%- end %>
    <% if klient_signed_in? %>
    <th>Zamówienie</th>
    <th></th>    
    <% end  %>   
    
  </tr>

<% @leks.each do |lek| %>
  <%= form_for :zamowieny, @zamowieny, :url => { :action => "create", :controller => "zamowienies" }, :html => {:class => "nifty_form"} do |f|  %>
  <tr>    
    <td><%= lek.NazwaLeku %></td>
    <td><%= lek.producent.NazwaProducenta %></td>
    <td><%= lek.Cena %></td>
    <td><%= lek.Ilosc %></td>
    <% if klient_signed_in? %>
      <td><%= f.number_field :Ilosc, :maxlength => 5, :size => 5  %></td>
      <%= hidden_field_tag 'zamowieny[uzytkownik_id]', current_klient.id %>
      <%= hidden_field_tag 'zamowieny[DataZamowienia]', Time.now %>
      <%= hidden_field_tag 'zamowieny[lek_id]', lek.id %>
    <% end %>
    <% if can? :read, @lek %>
    <td><%= link_to 'Pokaż', lek %></td>
    <%- end %>
    <% if can? :update, @lek %>
    <td><%= link_to 'Edytuj', edit_lek_path(lek) %></td>
    <%- end %>
    <% if can? :cancel, @lek %>
    <td><%= link_to 'Usuń', lek, :confirm => 'Czy na pewno?', :method => :delete %></td>
    <%- end %>
    <% if klient_signed_in? %>        
    <td><%= submit_tag "Zamow", :confirm => 'Czy na pewno chcesz zamowic wybrany przez siebie lek?' %></td>
    <% end %>
    <%- end %>
  </tr>

  <% end %>
  </table>

<br />
<% if can? :create, @lek %>
<%= link_to 'Nowy lek', new_lek_path %>
<%- end %>

HurtowniaLekow/app/views/leks/new.html.erb
<h1>Nowy lek</h1>

<%= render 'form' %>

<%= link_to 'Powrót', leks_path %>

HurtowniaLekow/app/views/leks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nazwa:</b>
  <%= @lek.NazwaLeku %>
</p>
<p>
  <b>Producent:</b>
  <%= @lek.producent.NazwaProducenta %>
</p>
<p>
  <b>Cena:</b>
  <%= @lek.Cena %>
</p>
<p>
  <b>Ilość:</b>
  <%= @lek.Ilosc %>
</p>
<%= link_to 'Edytuj', edit_lek_path(@lek) %> |
<%= link_to 'Powrót', leks_path %>