HurtowniaLekow/config/routes.rb
HurtowniaLekow::Application.routes.draw do

  resources :zamowienies

  
  resources :pracowniks, :path => "/editpracowniks"

  resources :admins, :controller => :pracowniks, :path => "/editpracowniks"

  resources :producents

  resources :leks

  devise_for :klients

  devise_for :pracowniks, :controllers => { :registrations => "pracowniks/registrations" }

  devise_for :admins, :controllers => { :registrations => "admins/registrations" }
  
  get "stronaglowna/index"
  

  match '/zamowienies/new' => 'zamowienies#new'
  match '/' => 'stronaglowna#index', :as => :index
  match '/leks' => 'leks#index', :as => :leksindex
  match '/zamowienies' => 'zamowienies#index', :as => :zamowieniesindex
  match '/producents' => 'producents#index', :as => :producentsindex
  match '/editpracowniks' => 'pracowniks#index', :as => :pracowniksindex
  
  
  

  root :to => "stronaglowna#index"

end

HurtowniaLekow/app/models/zamowieny.rb
class Zamowieny < ActiveRecord::Base
  validates :uzytkownik_id, :presence => true
  validates :lek_id, :presence => true
  validates :Ilosc, :presence => true
  validates :DataZamowienia, :presence => true

  belongs_to :uzytkownik
  belongs_to :lek
  has_many :zamowienie_pracowniks
  has_many :pracowniks, :through => :zamowienie_pracowniks

end

HurtowniaLekow/app/controllers/zamowienies_controller.rb
class ZamowieniesController < ApplicationController
 load_and_authorize_resource
  # GET /zamowienies
  # GET /zamowienies.xml
  def index    
    @zamowienies = Zamowieny.all
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @zamowienies }
    end
  end

  # GET /zamowienies/1
  # GET /zamowienies/1.xml
  def show
    @zamowieny = Zamowieny.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @zamowieny }
    end
  end

  # GET /zamowienies/new
  # GET /zamowienies/new.xml
  def new
    @zamowieny = Zamowieny.new(params[:zamowieny])
    

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @zamowieny }
    end
  end

  # GET /zamowienies/1/edit
  def edit
    @zamowieny = Zamowieny.find(params[:id])
  end

  # POST /zamowienies
  # POST /zamowienies.xml
  def create
    @zamowieny = Zamowieny.new(params[:zamowieny])
    

    respond_to do |format|
      if(@zamowieny.Ilosc.nil?)
        format.html { redirect_to(leks_url , :notice => 'Prosze wprowadzic ilosc leku.') }
      elsif(@zamowieny.Ilosc < 10 or @zamowieny.Ilosc > Lek.find(@zamowieny.lek_id).Ilosc )
        format.html { redirect_to(leks_url , :notice => 'Ilosc leku musi byc wieksza od 10 i mniejsza od ilosc leku w magazynie.') }
      elsif @zamowieny.save
        l = Lek.find(@zamowieny.lek_id)
        l.Ilosc = l.Ilosc - @zamowieny.Ilosc
        l.save
        format.html { redirect_to(@zamowieny, :notice => 'Zamowienie was successfully created.') }
        format.xml  { render :xml => @zamowieny, :status => :created, :location => @zamowieny }
        
      else
        format.html { render :action => "index" }
        format.xml  { render :xml => @zamowieny.errors, :status => :unprocessable_entity }
      end
      
    end
    
  end

  # PUT /zamowienies/1
  # PUT /zamowienies/1.xml
  def update
    @zamowieny = Zamowieny.find(params[:id])

    respond_to do |format|
      if @zamowieny.update_attributes(params[:zamowieny])
        format.html { redirect_to(@zamowieny, :notice => 'Zamowienie was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @zamowieny.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /zamowienies/1
  # DELETE /zamowienies/1.xml
  def destroy
    @zamowieny = Zamowieny.find(params[:id])
    @zamowieny.destroy

    respond_to do |format|
      format.html { redirect_to(zamowienies_url) }
      format.xml  { head :ok }
    end
  end
end

HurtowniaLekow/app/helpers/zamowienies_helper.rb
module ZamowieniesHelper
end

HurtowniaLekow/app/views/zamowienies/_form.html.erb
<%= form_for(@zamowieny) do |f| %>
  <% if @zamowieny.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zamowieny.errors.count, "error") %> prohibited this zamowieny from being saved:</h2>

      <ul>
      <% @zamowieny.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        
      <% end %>
      </ul>
    </div>
  
  <% end %>
  
  <div class="field">
    <%= f.label :Lek %><br />
    <%= collection_select(:zamowieny, :lek_id, Lek.all, :id, :NazwaLeku) %><br />
  </div>
  <div class="field">
    <%= f.label :Ilość %><br />
    <%= f.text_field :Ilosc, :value => @zamowieny.Ilosc %>
  </div>

  <%= hidden_field_tag 'zamowieny[uzytkownik_id]', current_klient.id %>
 
  <%= hidden_field_tag 'zamowieny[DataZamowienia]', Time.now %>
  

  <div class="actions">
    <%= f.submit :Zamow %>
  </div>
<% end %>

HurtowniaLekow/app/views/zamowienies/edit.html.erb
<h1>Editing zamowieny</h1>

<%= render 'form' %>

<%= link_to 'Show', @zamowieny %> |
<%= link_to 'Back', zamowienies_path %>

HurtowniaLekow/app/views/zamowienies/index.html.erb
<h1>Lista zamówień</h1>

<table>
  <tr>
    <th>Lek</th>
    <th>Ilość</th>
    <th>Data zamówienia</th>
    <th>Data realizacji</th>
    <% if can? :read, @zamowieny %><th></th><%- end %>
    <% if can? :update, @zamowieny %><th></th><%- end %>
    <% if can? :cancel, @zamowieny %><th></th><%- end %>
  </tr>

<% @zamowienies.each do |zamowieny| %>
  <tr>
    <td><%= zamowieny.lek.NazwaLeku %></td>
    <td><%= zamowieny.Ilosc %></td>
    <td><%= zamowieny.DataZamowienia %></td>
    <td><%= zamowieny.DataRealizacji %></td>
    <% if can? :read, @zamowieny %>
    <td><%= link_to 'Show', zamowieny %></td>
    <%- end %>
    <% if can? :update, @zamowieny %>
    <td><%= link_to 'Edit', edit_zamowieny_path(zamowieny) %></td>
    <%- end %>
    <% if can? :cancel, @zamowieny %>
    <td><%= link_to 'Destroy', zamowieny, :confirm => 'Are you sure?', :method => :delete %></td>
    <%- end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nowe zamówienie', new_zamowieny_path %>

HurtowniaLekow/app/views/zamowienies/new.html.erb
<h1>Nowe zamówienie</h1>

<%= render 'form' %>

<%= link_to 'Back', zamowienies_path %>

HurtowniaLekow/app/views/zamowienies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_zamowieny_path(@zamowieny) %> |
<%= link_to 'Back', zamowienies_path %>